channels:
  - conda-forge

dependencies:
  - python=3.10
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # nbgitpuller is very helpful when distributing user content
  - nbgitpuller
  # Specify major version of jupyterlab to use. Manually bump it when you want to upgrade
  # jupyterlab version
  - jupyterlab>=3.0,<4.0
  # This provides memory usage stats on JupyterLab and classic notebook
  - jupyter-resource-usage
  # https://syncthing.net/ provides a dropbox-like interface for syncing directories across users,
  # hubs and machines. Used along with `jupyter-syncthing-proxy` from pip.
  - syncthing
  # gh-scoped-creds allows users to securely push to GitHub from their repo.
  # https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f has
  # some more information
  - gh-scoped-creds

  # Cloud access tools and libraries
  # Access S3 easily from python
  - s3fs
  # handle login and similar details for accessing earthdata protected data
  # https://github.com/nsidc/earthaccess
  - earthdata
  # Access datasets exposed via STAC
  - pystac-client
  # Access datasets exposed via intake catalogs
  - intake
  - intake-esm
  - intake-xarray

  # Core scientific python stack
  - numpy
  - scipy
  - matplotlib
  - pandas
  - networkx
  - scikit-image
  - scikit-learn
  - sympy
  - statsmodels
  - xarray
  - hypothesis # needed by numpy testing tools
  - cython  # optimization, C API access
  - numba  # high-performance numerics

  # Jupyter tools
  - ipython
  - ipywidgets
  - jupyterlab-favorites
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyter-book
  - nbconvert
  - nbdime

  # Visualization packages
  - cartopy # geospatial plotting with matplotlib
  - seaborn  # statistical plotting with matplotlib
  - ipympl # This enables matplotlib interaction with jupyter widgets
  - ipyleaflet
  - bokeh
  - plotly

  # Geospatial data packages
  - geopandas
  - rasterio
  - rioxarray
  - xarray-datatree

  # File formats and file management, download, dataset caching
  - h5py
  - hdf5
  - h5netcdf
  - pooch

  # Distributed computing
  - dask
  - dask-labextension

  # Other useful generic python packages
  - pillow # Python imaging library, useful for many image-related tasks
  - tqdm  # progress bars, with notebook support
  - pytest
  - pytest-cov
  - pep8
  - flake8
  
  # Packages specific to cryo work
  - icepyx

  # Not all packages will be available from conda-forge, we install from pip when we need to.
  - pip
  - pip:
      - jupyter-syncthing-proxy

      # Access linux desktop from inside JupyterHub
      - jupyter-desktop-server
