channels:
  - conda-forge

dependencies:
  - python=3.10
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # nbgitpuller is very helpful when distributing user content
  - nbgitpuller
  # Specify major version of jupyterlab to use. Manually bump it when you want to upgrade
  # jupyterlab version
  - jupyterlab>=3.0,<4.0
  # This provides memory usage stats on JupyterLab and classic notebook
  - jupyter-resource-usage
  # https://syncthing.net/ provides a dropbox-like interface for syncing directories across users,
  # hubs and machines. Used along with `jupyter-syncthing-proxy` from pip.
  - syncthing
  # gh-scoped-creds allows users to securely push to GitHub from their repo.
  # https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f has
  # some more information
  - gh-scoped-creds

  # Packages specific to cryo work
  - icepyx==0.6.4

  # Not all packages will be available from conda-forge, we install from pip when we need to.
  - pip
  - pip:
      - jupyter-syncthing-proxy==1.0.3
